apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
      - name: fastapi-demo
        image: fastapi-demo:latest
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8000
        env:
        - name: PRIMARY_DB_URL
          value: "postgresql://app_user:change-me-in-production@pg-demo-cluster-rw:5432/app_db"
        - name: REPLICA_DB_URL
          value: "postgresql://app_user:change-me-in-production@pg-demo-cluster-r:5432/app_db"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
spec:
  selector:
    app: fastapi-demo
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer 