apiVersion: v1
kind: Secret
metadata:
  name: app-user-secret
type: Opaque
stringData:
  username: app_user
  password: change-me-in-production  # Change this in production!
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
stringData:
  ACCESS_KEY_ID: minioadmin      # Same as MINIO_ROOT_USER
  ACCESS_SECRET_KEY: minioadmin   # Same as MINIO_ROOT_PASSWORD
